v1 = input('Digite algo aqui:')
print(type(v1))
print('É alfabético?', v1.isalpha())
print('É numérico?', v1.isnumeric())
print('É alfa-numérico?', v1.isalnum())
print('É um dígito?', v1.isdigit())
print('É um código em ascii?', v1.isascii())
print('É um número decimal?', v1.isdecimal())
print('Tem espaços?', v1.isspace())
